name: Deploy Web App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

            # Cache Gradle dependencies and build outputs to speed up future builds
      - name: Cache Gradle and build outputs
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
            build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build Web(JS) App
        shell: bash
        run: ./gradlew jsBrowserDistribution

      # Save web app as artifact
      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: './${{ inputs.web_package_name }}/build/distributions'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './${{ inputs.web_package_name }}/build/distributions'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
